### ISSUE TITLE
Copy and enhance About US section in the Website to the repo 

### ISSUE THREAD

**Issue by OmarShawky1** [OmarShawky1/ACU#4]
# Request
1. Copy everything under the About US except Board of Leaders. (It is a holder place at the moment)
2. Suggest, if you feel like, where to put Mentors and Board of Leaders.
3. Suggest where to put the Mission section or even merge it with the README summary.

# Suggestion
Add everything under "About US" in the [website](https://www.activecourses.tech/) into the repo.

As where  to add it, I personally think that only mentors and Board of Leaders should be at the top in the [README](https://github.com/OmarShawky1/ACU/blob/main/README.md). Meanwhile, the rest should be in the [Explanation beside ACU Comparison](https://github.com/OmarShawky1/ACU/blob/main/README-Explanation.md#acu-comparison) or like in OSSU, at the bottom of the README.

**Comment by yosifshaban6** [comment]
Here is an enhancement to the Mentors and Leaders section. Could you leave your comments?

## Special Thanks for these Wonderful People

<table width="100%">
  <tbody>
    <tr>
      <td align="center" valign="top">
        <a href="https://github.com/AhalimZaki">
          <img src="https://avatars.githubusercontent.com/u/23334080?v=4" width="100px" height="100px" alt="DevOps Mentor" /><br />
          <sub><b>Abdelhalim Zaki</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/abdelhalimzaki/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
      </td>
      <td align="center" valign="top">
        <a href="https://github.com/OmarShawky1">
          <img src="https://avatars.githubusercontent.com/u/51538094?v=4" width="100px" height="100px" alt="ACU Creator" /><br />
          <sub><b>Omar Shawky</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/omarshawky1/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
        <a href="https://omarshawky1.github.io/portfolio/">
          <img src="https://www.activecourses.tech/img/website-dark.svg" width="15px" height="15px" />
        </a>
      </td>
    </tr>
  </tbody>
</table>

**Comment by OmarShawky1** [comment]
@Youssef1S They look great. I think you missed out that feature beanch that already contains a similar approach. Perhaps contributing using it will ease up the effort required.

**Comment by Youssef1S** [comment]
I've already seen it but my approach has more details. If you want me to complete the feature branch approach, I'll do it.

**Comment by yosifshaban6** [comment]
> @Youssef1S They look great. I think you missed out that feature beanch that already contains a similar approach. Perhaps contributing using it will ease up the effort required.


I've already seen it but my approach has more details. If you want me to complete the feature branch approach, I'll do it.

**Extra Suggestion**
What do you think about putting all of them on the same table but each row expresses a different role?

**Comment by OmarShawky1** [comment]
@Youssef1S For the sectioning, please follow the feature branch because it follows same structure as website.

**Comment by yosifshaban6** [comment]
## Special Thanks for these Wonderful People

### Mentors

<table width="100%">
  <tbody>
    <tr>
      <td align="center" valign="top">
        <a href="https://github.com/AhalimZaki">
          <img src="https://avatars.githubusercontent.com/u/23334080?v=4" width="100px" height="100px" alt="DevOps Mentor" /><br />
          <sub><b>Abdelhalim Zaki</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/abdelhalimzaki/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
      </td>
    </tr>
  </tbody>
</table>

### Board Of Leaders

<table width="100%">
   <tbody>
    <tr>
      <td align="center" valign="top">
        <a href="https://github.com/OmarShawky1">
          <img src="https://avatars.githubusercontent.com/u/51538094?v=4" width="100px" height="100px" alt="ACU Creator" /><br />
          <sub><b>Omar Shawky</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/omarshawky1/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
        <a href="https://omarshawky1.github.io/portfolio/">
          <img src="https://www.activecourses.tech/img/website-dark.svg" width="15px" height="15px" />
        </a>
      </td>
    </tr>
   </tbody>
</table>

### Curriculum Maintainers

<table width="100%">
   <tbody>
    <tr>
      <td align="center" valign="top">
        <a href="https://github.com/xUser5000">
          <img src="https://avatars.githubusercontent.com/u/40672207?v=44" width="100px" height="100px" alt="Curriculum Maintainer" /><br />
          <sub><b>Abdullah Ahmed</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/xUser5000/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
        <a href="https://xuser5000.hashnode.dev/">
          <img src="https://www.activecourses.tech/img/website-dark.svg" width="15px" height="15px" />
        </a>
      </td>
    </tr>
   </tbody>
</table>

### Contributers

<table width="100%">
   <tbody>
    <tr>
      <td align="center" valign="top">
         <img src="https://avatars.githubusercontent.com/u/12874707?v=4" width="100px" height="100px" alt="Moderator" /><br />
        <a href="">
          <sub><b>Mohammed A. Gomaa</b></sub>
        </a><br />
      </td>
      <td align="center" valign="top">
         <img src="https://avatars.githubusercontent.com/u/37001450?v=4" width="100px" height="100px" alt="Moderator" /><br />
        <a href="https://github.com/3ein39">
          <sub><b>Hussein Hany</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/3ein39/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
        <a href="https://3ein39.me/">
          <img src="https://www.activecourses.tech/img/website-dark.svg" width="15px" height="15px" />
        </a>
      </td>
      <td align="center" valign="top">
         <img src="https://avatars.githubusercontent.com/u/64869057?v=4" width="100px" height="100px" alt="Moderator" /><br />
        <a href="#">
          <sub><b>Hussein Hany</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/yasserahmeddev">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
      </td>
      <td align="center" valign="top">
         <img src="https://www.activecourses.tech/img/avatar.png" width="100px" height="100px" alt="Moderator" /><br />
        <a href="#">
          <sub><b>Abdulrahman Al-Ghamdi</b></sub>
        </a><br />
      </td>
      <td align="center" valign="top">
         <img src="https://avatars.githubusercontent.com/u/29659555?v=4" width="100px" height="100px" alt="Website Maintainer" /><br />
        <a href="https://github.com/alikehel">
          <sub><b>Ali Kehel</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/alikehel">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
      </td>
      <td align="center" valign="top">
         <img src="https://avatars.githubusercontent.com/u/86894852?v=4" width="100px" height="100px" alt="Moderator" /><br />
        <a href="#">
          <sub><b>Abdallah Elhadad</b></sub>
        </a><br />
      </td>
    </tr>
    <tr>
      <td align="center" valign="top">
         <img src="https://www.activecourses.tech/img/avatar.png" width="100px" height="100px" alt="Moderator" /><br />
        <a href="#">
          <sub><b>Mohamed Ashraf</b></sub>
        </a><br />
      </td>
      <td align="center" valign="top">
         <img src="https://www.activecourses.tech/img/avatar.png" width="100px" height="100px" alt="Moderator" /><br />
        <a href="#">
          <sub><b>Ramadan Yasin</b></sub>
        </a><br />
      </td>
     </tr>
   </tbody>
</table>

**Comment by yosifshaban6** [comment]
Here we are, what do you think? 
Do you want to repeat the people in different sections as website?

**Comment by OmarShawky1** [comment]
Looks great! Please add it

**Comment by yosifshaban6** [comment]
Ok I added them.
Do you want me to push them in feat-AboutUs branch?

## Special Thanks for these Wonderful People

### Mentors

<table width="100%">
  <tbody>
    <tr>
      <td align="center" valign="top">
        <a href="https://github.com/AhalimZaki">
          <img src="https://avatars.githubusercontent.com/u/23334080?v=4" width="100px" height="100px" alt="DevOps Mentor" /><br />
          <sub><b>Abdelhalim Zaki</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/abdelhalimzaki/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
      </td>
    </tr>
  </tbody>
</table>

### Board Of Leaders

<table width="100%">
   <tbody>
    <tr>
      <td align="center" valign="top">
        <a href="https://github.com/OmarShawky1">
          <img src="https://avatars.githubusercontent.com/u/51538094?v=4" width="100px" height="100px" alt="ACU Creator" /><br />
          <sub><b>Omar Shawky</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/omarshawky1/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
        <a href="https://omarshawky1.github.io/portfolio/">
          <img src="https://www.activecourses.tech/img/website-dark.svg" width="15px" height="15px" />
        </a>
      </td>
    </tr>
   </tbody>
</table>

### Curriculum Maintainers

<table width="100%">
   <tbody>
    <tr>
      <td align="center" valign="top">
        <a href="https://github.com/OmarShawky1">
          <img src="https://avatars.githubusercontent.com/u/51538094?v=4" width="100px" height="100px" alt="ACU Creator" /><br />
          <sub><b>Omar Shawky</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/omarshawky1/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
        <a href="https://omarshawky1.github.io/portfolio/">
          <img src="https://www.activecourses.tech/img/website-dark.svg" width="15px" height="15px" />
        </a>
      </td>
      <td align="center" valign="top">
        <a href="https://github.com/xUser5000">
          <img src="https://avatars.githubusercontent.com/u/40672207?v=44" width="100px" height="100px" alt="Curriculum Maintainer" /><br />
          <sub><b>Abdullah Ahmed</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/xUser5000/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
        <a href="https://xuser5000.hashnode.dev/">
          <img src="https://www.activecourses.tech/img/website-dark.svg" width="15px" height="15px" />
        </a>
      </td>
    </tr>

   </tbody>
</table>

### Contributers

<table width="100%">
   <tbody>
    <tr>
      <td align="center" valign="top">
        <a href="https://github.com/OmarShawky1">
          <img src="https://avatars.githubusercontent.com/u/51538094?v=4" width="100px" height="100px" alt="ACU Creator" /><br />
          <sub><b>Omar Shawky</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/omarshawky1/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
        <a href="https://omarshawky1.github.io/portfolio/">
          <img src="https://www.activecourses.tech/img/website-dark.svg" width="15px" height="15px" />
        </a>
      </td>
      <td align="center" valign="top">
        <a href="https://github.com/xUser5000">
          <img src="https://avatars.githubusercontent.com/u/40672207?v=44" width="100px" height="100px" alt="Curriculum Maintainer" /><br />
          <sub><b>Abdullah Ahmed</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/xUser5000/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
        <a href="https://xuser5000.hashnode.dev/">
          <img src="https://www.activecourses.tech/img/website-dark.svg" width="15px" height="15px" />
        </a>
      </td>
      <td align="center" valign="top">
         <img src="https://avatars.githubusercontent.com/u/12874707?v=4" width="100px" height="100px" alt="Moderator" /><br />
        <a href="">
          <sub><b>Mohammed A. Gomaa</b></sub>
        </a><br />
      </td>
      <td align="center" valign="top">
         <img src="https://avatars.githubusercontent.com/u/37001450?v=4" width="100px" height="100px" alt="Moderator" /><br />
        <a href="https://github.com/3ein39">
          <sub><b>Hussein Hany</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/3ein39/">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
        <a href="https://3ein39.me/">
          <img src="https://www.activecourses.tech/img/website-dark.svg" width="15px" height="15px" />
        </a>
      </td>
      <td align="center" valign="top">
         <img src="https://avatars.githubusercontent.com/u/64869057?v=4" width="100px" height="100px" alt="Moderator" /><br />
        <a href="#">
          <sub><b>Hussein Hany</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/yasserahmeddev">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
      </td>
      <td align="center" valign="top">
         <img src="https://www.activecourses.tech/img/avatar.png" width="100px" height="100px" alt="Moderator" /><br />
        <a href="#">
          <sub><b>Abdulrahman Al-Ghamdi</b></sub>
        </a><br />
      </td>
    </tr>
    <tr>
      <td align="center" valign="top">
         <img src="https://avatars.githubusercontent.com/u/29659555?v=4" width="100px" height="100px" alt="Website Maintainer" /><br />
        <a href="https://github.com/alikehel">
          <sub><b>Ali Kehel</b></sub>
        </a><br />
        <a href="https://www.linkedin.com/in/alikehel">
          <img src="https://www.activecourses.tech/img/linkedin-dark.svg" width="15px" height="15px" />
        </a>
      </td>
      <td align="center" valign="top">
         <img src="https://avatars.githubusercontent.com/u/86894852?v=4" width="100px" height="100px" alt="Moderator" /><br />
        <a href="#">
          <sub><b>Abdallah Elhadad</b></sub>
        </a><br />
      </td>
      <td align="center" valign="top">
         <img src="https://www.activecourses.tech/img/avatar.png" width="100px" height="100px" alt="Moderator" /><br />
        <a href="#">
          <sub><b>Mohamed Ashraf</b></sub>
        </a><br />
      </td>
      <td align="center" valign="top">
         <img src="https://www.activecourses.tech/img/avatar.png" width="100px" height="100px" alt="Moderator" /><br />
        <a href="#">
          <sub><b>Ramadan Yasin</b></sub>
        </a><br />
      </td>
     </tr>
   </tbody>
</table>

**Comment by OmarShawky1** [comment]
No, this might be easier:
1. Fork.
2. Checkout feature branch.
3. Add your patch (your code).
4. PR onto main.
